// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwuG6v2w_IKFPH1dNlyzI5C3LYLJf1AI',
    appId: '1:897893225168:web:3926f0f0b4c67db94ac4d5',
    messagingSenderId: '897893225168',
    projectId: 'dan-login-flutter---firebase',
    authDomain: 'dan-login-flutter---firebase.firebaseapp.com',
    storageBucket: 'dan-login-flutter---firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCWRN7gkrOOUSD57nWCqEx--Mas2HRSLo',
    appId: '1:897893225168:android:2aec462051b7ff694ac4d5',
    messagingSenderId: '897893225168',
    projectId: 'dan-login-flutter---firebase',
    storageBucket: 'dan-login-flutter---firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfBYu0suf56Uwg6SqfQ6NsMBXR3ifABU',
    appId: '1:897893225168:ios:1a2b8d696108fea24ac4d5',
    messagingSenderId: '897893225168',
    projectId: 'dan-login-flutter---firebase',
    storageBucket: 'dan-login-flutter---firebase.appspot.com',
    iosClientId: '897893225168-unpoigun72pv5t3l4dbt5d83uo8bb7ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.danLoginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKfBYu0suf56Uwg6SqfQ6NsMBXR3ifABU',
    appId: '1:897893225168:ios:84aa52d4a975b0894ac4d5',
    messagingSenderId: '897893225168',
    projectId: 'dan-login-flutter---firebase',
    storageBucket: 'dan-login-flutter---firebase.appspot.com',
    iosClientId: '897893225168-mi05b4j4krk8c8n4bh2titfgp8fq0b1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.danLoginFlutter.RunnerTests',
  );
}
